baseURL = "http://1o0.jp/"
languageCode = "ja"
title = "1o0"
theme = "hugo-zen"
enableGitInfo = true
[permalinks]
blog = ":year:/:month:/:day/blog_:slug/"
diary = ":year:/:month:/:day/"
ymk = ":year:/:month/:day/:slug/"
archive_yearly = ":year/"
archive_monthly = ":year:/:month/"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
