baseURL = "http://1o0.jp/"
languageCode = "ja"
title = "1o0"
theme = "hugo-zen"
enableGitInfo = true
[permalinks]
blog = ":year:month:day/:section/:slug/"
diary = ":year:month:day/"
archive_yearly = ":year/"
archive_monthly = ":year:month/"
